apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: flavi-2
  janus-idp.io/tekton: flavi-2
  backstage.io/kubernetes-id: flavi-2
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: flavi-2
resources: 
- deployment.yaml
- route.yaml
- service.yaml
